trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'authservice'
    publishLocation: 'Container'
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'authservice'
    downloadPath: '$(Build.SourcesDirectory)'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/authservice'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/authservice.zip'
    replaceExistingArchive: true
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure per studenti (b0e160a4-e99f-42eb-85f8-f55409ad025b)'
    appType: 'webApp'
    appName: 'IUPUsesservice'
    package: '$(System.DefaultWorkingDirectory)/authservice.zip'
    deploymentMethod: 'runFromPackage'

